version: '3.7'

services:
  mongo:
    image: bitnami/mongodb:6.0
    container_name: mobilebe_mongo
    environment:
      MONGODB_ROOT_USER: ${DB_ROOT_USER}
      MONGODB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ADVERTISED_HOSTNAME: ${DB_HOST}
      MONGODB_REPLICA_SET_KEY: replicasetkey123
    ports:
      - ${DB_PORT}:27017
    volumes:
      - mongodb:/bitnami/mongodb/data
    tty: true
    restart: always

volumes:
  mongodb:
